# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bio-pipengine 0.9.6 ruby lib

Gem::Specification.new do |s|
  s.name = "bio-pipengine".freeze
  s.version = "0.9.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Francesco Strozzi".freeze, "Raoul Jean Pierre Bonnal".freeze]
  s.date = "2017-08-12"
  s.description = "A pipeline manager".freeze
  s.email = ["francesco.strozzi@gmail.com".freeze, "ilpuccio.febo@gmail.com".freeze]
  s.executables = ["pipengine".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "VERSION",
    "lib/bio-pipengine.rb",
    "lib/bio/pipengine.rb",
    "lib/bio/pipengine/job.rb",
    "lib/bio/pipengine/sample.rb",
    "lib/bio/pipengine/step.rb"
  ]
  s.homepage = "http://github.com/fstrozzi/bioruby-pipengine".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "A pipeline manager".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>.freeze, [">= 2.1.2"])
      s.add_runtime_dependency(%q<colorize>.freeze, [">= 0.8.1"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    else
      s.add_dependency(%q<trollop>.freeze, [">= 2.1.2"])
      s.add_dependency(%q<colorize>.freeze, [">= 0.8.1"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<trollop>.freeze, [">= 2.1.2"])
    s.add_dependency(%q<colorize>.freeze, [">= 0.8.1"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

