# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bio-pipengine 0.9.2 ruby lib

Gem::Specification.new do |s|
  s.name = "bio-pipengine"
  s.version = "0.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Francesco Strozzi", "Raoul Jean Pierre Bonnal"]
  s.date = "2016-04-27"
  s.description = "A pipeline manager"
  s.email = ["francesco.strozzi@gmail.com", "ilpuccio.febo@gmail.com"]
  s.executables = ["pipengine"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "VERSION",
    "lib/bio-pipengine.rb",
    "lib/bio/pipengine.rb",
    "lib/bio/pipengine/job.rb",
    "lib/bio/pipengine/sample.rb",
    "lib/bio/pipengine/step.rb"
  ]
  s.homepage = "http://github.com/fstrozzi/bioruby-pipengine"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "A pipeline manager"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
      s.add_runtime_dependency(%q<colorize>, [">= 0"])
      s.add_runtime_dependency(%q<warbler>, [">= 1.4.8"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<colorize>, [">= 0"])
      s.add_dependency(%q<warbler>, [">= 1.4.8"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<colorize>, [">= 0"])
    s.add_dependency(%q<warbler>, [">= 1.4.8"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

