module Bio
	module Pipengine
		
		# Step holds information for a pipeline step
		# groups_def is used to store information on groups definition (i.e. generic cmd lines with placeholders)
		# groups_cmd is used to store the actual command lines for all the samples to be combined in a "groups" step
		# this are generated by combining groups_def information with sample groups information and will be placed
		# where <groups> placeholder is found into the step command lines.
		class Step
			attr_accessor :name, :run, :cpus, :groups_def, :groups_cmd
			def initialize(name,step_instructions)
				@name = name
				parse_yaml(step_instructions)	
			end

			def is_group?
				return (self.groups_def.nil?) ? false : true
			end

			private

			def parse_yaml(step_instructions)
				self.cpus = step_instructions["cpu"].to_i
				self.run = step_instructions["run"]
				self.groups_def = step_instructions["groups"]
			end

		end

	end
end

